name: Test

on: [workflow_dispatch, pull_request]

permissions:
  contents: write

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: ./ # Uses action.yml in the root directory
        with:
          overleaf_url: ${{ vars.OVERLEAF_URL }}
          gdrive_link: ${{ vars.GDRIVE_LINK }}
          gdrive_service_account_key: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
